[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[dependencies]
engine_derive = { path = "../engine_derive" }
sdl2 = { version = "0.38.0", features = ["bundled"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
